### ISSUE TITLE
D-4 To-Do

### ISSUE THREAD

**Issue by huiso** [2021-SMHRD-IITP-AI/window_nodejs#39]
- [ ] 아이콘 수정
- [ ] 팝업창
- [ ] 폴더 북마크 출력
---------------------------------------------------------
- [ ] 선택북마크 인용구조 출력
- [ ] 인용구조 중 논문 선택 시 상단에 경로 출력
---------------------------------------------------------
- [ ] 선택 북마크 맵보기 기능구현 ★★★★★
---------------------------------------------------------
- [ ] 선택 북마크 리스트보기 기능구현
---------------------------------------------------------
- [ ] 북마크 메모기능 구현
- [ ] 북마크 폴더이동/삭제 기능구현
---------------------------------------------------------
- [ ] UI 디자인
---------------------------------------------------------
- [ ] PPT 작성
- [ ] 발표준비
